tools:
    php_code_sniffer:
        command: wget -O /tmp/noviusos.xml http://raw.github.com/novius-os/ci/master/0.2/phpcs/ruleset.xml;phpcs -n
        config:
            standard:   /tmp/noviusos.xml
            severity:             5
            error_severity:       5
            warning_severity:     0
